name: "Dropbox HA Backup"
version: "0.5.7"
slug: "dropbox_ha_backup"
description: "Back up Home Assistant snapshots to Dropbox"
url: "https://github.com/zeynalnia/Home-Assistant-Plugins"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
hassio_api: true
hassio_role: "backup"
homeassistant_api: true
map:
  - config:rw
stdin: true
init: false
ingress: true
ingress_port: 8099
options:
  dropbox_app_key: ""
  dropbox_app_secret: ""
  automatic_backup: true
  backup_interval_hours: 24
  max_backups_in_dropbox: 10
  dropbox_backup_path: "/HomeAssistant/Backups"
schema:
  dropbox_app_key: str
  dropbox_app_secret: password
  automatic_backup: bool
  backup_interval_hours: int
  max_backups_in_dropbox: int
  dropbox_backup_path: str
